services:
  public-pool-ui:
    image: smolgrrr/public-pool-ui:8cd2563
    container_name: public-pool-ui
    environment:
      # Tell the frontend where the API lives, from the browser's point of view.
      # We're gonna serve /api from Caddy and forward it to Umbrel.
      - PUBLIC_POOL_API_URL=/api
    ports:
      - "2019:80"
    volumes:
      # Mounts the customized frontend into the container’s web root
      - "./custom-ui/html:/usr/share/nginx/html:ro"
    restart: always